### ISSUE TITLE
rwa for logistic regression

### ISSUE THREAD

**Issue by marvinneumann1108** [martinctc/rwa#11]
I have one question regarding the package: I want to calculate relative weights for a logistic regression, so a dichotomous outcome variable. Your rwa() function does not show an error message and puts out some relative weights. However, I am unsure whether your function is also applicable for logistic regression or whether I should not interpret those weights because the function assumes a continuous outcome variable?

Also, it is not entirely clear to me what approach you took to calculate relative weights. For example, how does your package compare to the "lmg" option in the relaimpo package?

**Comment by martinctc** [comment]
Hi @marvinneumann1108 - thanks for your question. We currently don't have logistic regression available in the CRAN or development version, but we have it in a pull request #7. It's still being worked on - and I'm not sure whether you can interpret the weights as they are. It's best to refer to Tonidandel and LeBreton's original paper, because this package merely implements what they set up originally. 

I'd recommend reading this paper: https://www.researchgate.net/profile/Jeff-Johnson/publication/40455316_Determining_the_Statistical_Significance_of_Relative_Weights/links/09e4150cb66c7c099a000000/Determining-the-Statistical-Significance-of-Relative-Weights.pdf

Also check out the papers listed in our README. In short, I believe the outputs in 'rwa' are for practically similar to the outputs of 'relaimpo', but the main difference is the performance, where the latter will take forever if you have 15+ predictors. The Q Analysis software (proprietary) also uses this approach where they switch to relative weights beyond a number of predictors.

**Comment by marvinneumann1108** [comment]
Hi @martinctc, great, thanks for your answer, the tips, and the literature!
